services:
  postgres:
    image: postgres:13
    container_name: ai_doctor_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_doctor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: ai_doctor_backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/ai_doctor_db
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: ai_doctor_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: